### ISSUE TITLE
Several upgrades / mechanics still have the "Cost" wording

### ISSUE THREAD

**Issue by James103** [WYXkk/ADfree#1]
In all of the below cases, the word "Cost" should be replaced with the word "Requirement" or its abbreviation "Req" to fit in with the theme of the mod.

* Time Dimensions
![image](https://github.com/user-attachments/assets/19d557ad-7f57-44e9-9124-8f8263eaf207)

* Various texts which describe cost scaling
![image](https://github.com/user-attachments/assets/5b70e2b9-cd7f-4e09-9f97-4bd0580223a7)
![image](https://github.com/user-attachments/assets/a00ef4b1-b8c9-472c-8fe2-5d58e4377fa0)
![image](https://github.com/user-attachments/assets/44ce5f73-ee6a-46ae-82d1-c0c9af55f0be)

* The upgrade which unlocks the first Black Hole
![image](https://github.com/user-attachments/assets/ebffa5dd-0b49-4441-ac37-2624b898931d)

* The Fragmentation, Recollection, and Level Up upgrades for each of the Celestial Memories within Ra
![image](https://github.com/user-attachments/assets/9168fd3b-b720-4f2e-8f66-c13b834e3a2c)

**Comment by WYXkk** [comment]
All above scenarios fixed; deployment will start later
