### ISSUE TITLE
Double-use of the word "requirement" in some Time Studies

### ISSUE THREAD

**Issue by James103** [WYXkk/ADfree#2]
The Time Studies which unlock Eternity Challenges, Time Dilation, and Reality use the word "requirement" twice, one to refer to the requirement present in the base game and once more (abbreviated as "req") in place of "cost" because Time Studies, like all other mechanics, only require resources, not cost.

Would it be possible to combine the two mentions of the word "requirement" into a single string with only a single mention of "requirement"? Doing so requires conditionally showing what used to be the cost line on the Time Studies, which may need non-trivial changes.

(All three examples are taken from the same game state, itself right after one of the first few Eternities.)
Example 1:
![image](https://github.com/user-attachments/assets/e47805fe-3b5a-4b7e-9679-88323854571c)
My fixed text: "Requirement: 4/160 Antimatter Galaxies and 141 Time Theorems"

Example 2:
![image](https://github.com/user-attachments/assets/c00a0243-eabd-4925-ad8d-889051f8219d)
My fixed text: "Requirement: 5 EC11 and EC12 completions and 8/12,900 total Time Theorems" (the "Req: 7,113 Time Theorems" line can be dropped as it is superseded by the 12,900 total TT requirement.)

Example 3:
![image](https://github.com/user-attachments/assets/6a967ee4-69f8-4804-a65d-f06a14bbe86f)
My fixed text: "Requirement: 1e4000 Eternity Points, 13 rows of Achievements, and 1e9 Time Theorems"

Post-Reality, once all perks are obtained, Examples 1 and 2 have their secondary requirements dropped, so it is fine to leave the displays it the same as vanilla (except, of course, with "Cost" swapped out for "Req.")

![image](https://github.com/user-attachments/assets/f7509afe-7de8-42c5-8252-ace8cfce9978)
However, Example 3 still has "Requirement: 1e4000 Eternity Points \n Req: 1e9 Time Theorems" as shown above, which can be rewritten as "Requirement: 1e4000 Eternity Points and 1e9 Time Theorems"

**Comment by WYXkk** [comment]
For your example 1 and 3, the "Req:" is now replaced with "and". Example 3 also now uses commas to concate the requirements when there are three.
For your example 2, the "Req: 7113 TT" is now dropped until DILR. DILR is also reworded to fit this change.
