### ISSUE TITLE
Can't pick new Perks for several Realities when importing a save with some, but not all, Perks bought

### ISSUE THREAD

**Issue by James103** [WYXkk/ADfree#3]
Self-explanatory. To test:
1. Import the "5 Realities/e6100 EP" save from https://buck4437.github.io/save-bank/#Reality.
2. Go to the Perks tab.
3. Notice you have 0 Perk Points and 5 perks bought (this state is otherwise unreachable without console).
4. Make a new Reality.
5. Notice that you can't pick a new Perk, as you only have 1 out of the 6 Perk Points required.

Alternatively,
1. Import the "8 Realities" save from https://buck4437.github.io/save-bank/#Reality.
2. Go to the Perks tab.
3. Notice you have 1 Perk Point and 7 perks bought, and that you can't pick a new Perk.

The net effect is that once importing a save into this mod, you are unable to pick new Perks for a number of Realities based on the number of unspent Perk Points and Perks bought, which can be quite high (over 40 Realities just to get the last perk).

**Comment by WYXkk** [comment]
oops. I forgot perk point is another resource like TT and should get a refund.

**Comment by WYXkk** [comment]
By the way, I'm not going to give everything a refund, like things that you have a lot. Prestige resource of latest layer is arguable but I'm lazy.
