### ISSUE TITLE
Time Study tree import modal is broken

### ISSUE THREAD

**Issue by James103** [WYXkk/ADfree#6]
The modal says no Time Studies will be purchased, regardless of the inputted tree and Time Theorem amount.
![image](https://github.com/user-attachments/assets/ec424a36-0aec-44c5-9ebc-882c31b1c532)

**Comment by WYXkk** [comment]
huh, never thought this will break
let me have a look

**Comment by WYXkk** [comment]
it decides whether it is empty by if there is a cost, but as this mod states there is no cost. lol
