### ISSUE TITLE
Galaxy Generator disappears when sacrificing the final Rift

### ISSUE THREAD

**Issue by James103** [WYXkk/ADfree#8]
When the Galaxy Generator reaches the state where it has to drain the Rift which unlocked it to continue, going through with that Rift drain causes the Galaxy Generator to disappear until all Rifts are filled again as part of the Galaxy Generator's final phase.

To reproduce, import the attached save and click the button in the Galaxy Generator to sacrifice the final Rift.
[save8.txt](https://github.com/user-attachments/files/16488355/save8.txt)

**Comment by WYXkk** [comment]
known, but don't affect much so low priority

**Comment by WYXkk** [comment]
find the reason: galaxy generator is displayed when that milestone is active or there is galaxies spent
and obviously, this mod make there is no spent galaxies
